### ISSUE TITLE
Integrate with coveragepy

### ISSUE THREAD

**Issue by antazoey** [ericnordelo/nile-coverage#11]
It would be nice if there was a coveragepy FileTracer for Cairo files to use with the `coverage` python tool.
That way, the report could merge with other reports and hook in with `pytest-cov` better.

**Comment by ericnordelo** [comment]
Hi @antazoey. Sounds interesting, but this is a plugin for the Python version of Nile, that is no longer maintained. We must explore new mechanisms for providing coverage, probably from the new compiler [test-runner crate](https://github.com/starkware-libs/cairo/tree/v1.0.0-rc0/crates/cairo-lang-test-runner), and those tests are written in Cairo itself, not python.

**Comment by antazoey** [comment]
that makes sense.  i am still interested in testing cairo with python anyway! so i may need to build some sort of coverageoy plugin.
