### ISSUE TITLE
Log output message before coverage report

### ISSUE THREAD

**Issue by andrew-fleming** [ericnordelo/nile-coverage#6]
The logging message: "Generating coverage report. This can take a minute..." (from [here](https://github.com/ericnordelo/nile-coverage/blob/main/src/nile_coverage/vendor/cairo_coverage.py#L17-L18)) appears only after the coverage report instead of before.

**Comment by ericnordelo** [comment]
Hi @andrew-fleming! Thank you for submitting the issue.

I see the message appearing before the report and not after, maybe what you mean is after running the tests? 

The purpose of that message is not to make the user aware of the time he needs to wait to run the test suite, but for a few seconds he needs to wait after the tests and before the report is printed (files with 0 coverage need to be compiled to show correct line count).

Maybe the message can be updated to be more descriptive? Any suggestion would be super appreciated.

**Comment by andrew-fleming** [comment]
Hey @ericnordelo! Ahh thank you, yes. For whatever reason, it just felt intuitive that this line precedes the tests themselves. I take it back, it's working as it should :) I think the message is perfect
